name: Build ASP.NET Framework App
env:
  AZURE_WEBAPP_NAME: SFinfotechwebapp01
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: windows-latest
    env:
      BuildPlatform: 'Any CPU'
      BuildConfiguration: 'Release'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: 'latest'

    - name: Restore NuGet packages
      run: |
        $solution = Get-ChildItem -Path . -Recurse -Filter *.sln | Select-Object -First 1
        if (-not $solution) { throw "No .sln file found in repo" }
        Write-Host "Restoring packages for $($solution.FullName)"
        nuget restore "$($solution.FullName)"
      shell: pwsh

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[17.0,)'   # VS 2022 or later

    - name: Build Solution
      run: |
        msbuild $env:Solution `
        /p:WebPublishMethod=FileSystem `
        /p:DeployOnBuild=true `
        /p:PublishUrl="$(Build.ArtifactStagingDirectory)" `
        /p:SkipInvalidConfigurations=true `
        /p:Platform="$env:BuildPlatform" `
        /p:Configuration="$env:BuildConfiguration"
      shell: pwsh

    - name: Copy JSON config files
      run: |
        mkdir -p drop\json
        Get-ChildItem -Path . -Recurse -Include *.json | Copy-Item -Destination drop\json
      shell: pwsh

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: drop
        path: drop
 # -------------------------------
    # 7️⃣ Deploy to Azure App Service
 # -------------------------------
    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        #client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
        
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.BUILD_ARTIFACTSTAGINGDIRECTORY }}
