name: Build ASP.NET Framework App

on:
  push:
    branches: none

jobs:
  build:
    runs-on: windows-latest
    env:
      BuildPlatform: 'Any CPU'
      BuildConfiguration: 'Release'
      PackageLocation: '${{ github.workspace }}\drop'
      ReferencePath: '${{ github.workspace }}\Libs'
      SymbolPath: '${{ github.workspace }}\Symbols'
      ArtifactName: 'drop'
      ArtifactPath: '${{ github.workspace }}\artifact'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: 'latest'

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        $solution = Get-ChildItem -Path . -Recurse -Filter *.sln | Select-Object -First 1
        if (-not $solution) { throw "No .sln file found in repo" }
        Write-Host "Restoring packages for $($solution.FullName)"
        nuget restore "$($solution.FullName)"

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '17.0'

    - name: Build and Package Solution
      shell: pwsh
      run: |
        $sln = Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1
        if (-not $sln) { throw "No .sln file found in repository" }

        $publishDir = "${{ env.PackageLocation }}"
        New-Item -Path $publishDir -ItemType Directory -Force | Out-Null

        Write-Host "Building and packaging solution: $($sln.FullName)"
        msbuild "$($sln.FullName)" `
          /p:DeployOnBuild=true `
          /p:WebPublishMethod=Package `
          /p:PackageAsSingleFile=true `
          /p:SkipInvalidConfigurations=true `
          /p:PackageLocation="$publishDir" `
          /p:IncludeServerNameInBuildInfo=true `
          /p:GenerateBuildInfoConfigFile=true `
          /p:BuildSymbolStorePath="${{ env.SymbolPath }}" `
          /p:ReferencePath="${{ env.ReferencePath }}" `
          /p:Platform="${{ env.BuildPlatform }}" `
          /p:Configuration="${{ env.BuildConfiguration }}" `
          /p:VisualStudioVersion="17.0"

        Write-Host "Build completed. Packages stored in: $publishDir"

    - name: Copy build output and JSON files to artifact staging directory
      shell: pwsh
      run: |
        $source = "${{ github.workspace }}"
        $drop   = "${{ env.PackageLocation }}"
        $target = "${{ env.ArtifactPath }}"

        Write-Host "Combining build output and JSON files into $target"

        New-Item -Path $target -ItemType Directory -Force | Out-Null

        # Copy build output
        if (Test-Path $drop) {
          Copy-Item -Path "$drop\*" -Destination $target -Recurse -Force
        }

        # Copy JSON files (keep directory structure)
        Get-ChildItem -Path $source -Recurse -Filter *.json -File |
          ForEach-Object {
            $relativePath = $_.FullName.Substring($source.Length).TrimStart('\')
            $destPath = Join-Path $target $relativePath
            $destDir = Split-Path $destPath
            if (-not (Test-Path $destDir)) {
              New-Item -Path $destDir -ItemType Directory -Force | Out-Null
            }
            Copy-Item $_.FullName -Destination $destPath -Force
          }

        Write-Host "Copied build output and JSON files successfully to $target"


    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ArtifactName }}
        path: ${{ env.ArtifactPath }}
