name: Build and Deploy ASP.NET App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write       # Needed for OIDC login to Azure
  contents: read

env:
  BuildPlatform: "Any CPU"
  BuildConfiguration: "Release"

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # ✅ Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # ✅ Step 2: Restore NuGet packages
    - name: Restore NuGet packages
      run: |
        $solution = Get-ChildItem -Path ${{ github.workspace }} -Filter *.sln -Recurse | Select-Object -First 1
        if (-not $solution) { throw "❌ No .sln file found in repository" }
        Write-Host "✅ Found solution file: $($solution.FullName)"
        nuget restore $solution.FullName
      shell: pwsh

    # ✅ Step 3: Build and publish using MSBuild
    - name: Build solution
      run: |
        $solution = Get-ChildItem -Path ${{ github.workspace }} -Filter *.sln -Recurse | Select-Object -First 1
        if (-not $solution) { throw "❌ No .sln file found" }

        # Locate MSBuild on the GitHub Windows runner
        $msbuild = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" `
          -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
        if (-not $msbuild) { throw "❌ MSBuild not found on runner" }

        Write-Host "✅ Using MSBuild at: $msbuild"
        & "$msbuild" $solution.FullName `
          /p:Configuration=Release `
          /p:Platform="Any CPU" `
          /p:DeployOnBuild=true `
          /p:WebPublishMethod=FileSystem `
          /p:DeleteExistingFiles=true `
          /p:publishUrl="${{ github.workspace }}\publish"
      shell: pwsh

    # ✅ Step 4: Login to Azure (OIDC)
    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # ✅ Step 5: Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: "SFinfotechwebapp01"   # 🔹 Replace with your Web App name
        package: "${{ github.workspace }}\\publish"
