name: Build and Deploy ASP.NET App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write       # needed for OIDC authentication
  contents: read

env:
  BuildPlatform: "Any CPU"
  BuildConfiguration: "Release"

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 🔹 Automatically find the .sln file and restore NuGet packages
    - name: Restore NuGet packages
      run: |
        $solution = Get-ChildItem -Path ${{ github.workspace }} -Filter *.sln -Recurse | Select-Object -First 1
        if (-not $solution) { throw "❌ No .sln file found in repository" }
        Write-Host "✅ Found solution file: $($solution.FullName)"
        nuget restore $solution.FullName
      shell: pwsh

    # 🔹 Build the solution (Release mode)
    - name: Build solution
      run: |
        $solution = Get-ChildItem -Path ${{ github.workspace }} -Filter *.sln -Recurse | Select-Object -First 1
        msbuild $solution.FullName /p:Configuration=Release /p:Platform="Any CPU" /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=true /p:publishUrl="${{ github.workspace }}\publish"
      shell: pwsh

    # 🔹 Login to Azure using Federated Identity (OIDC)
    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # 🔹 Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: "SFinfotechwebapp01"   # <-- change this to your Web App name
        package: "${{ github.workspace }}\\publish"
