name: Build and Deploy ASP.NET Framework App to Azure WebApp (OIDC)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write        # ✅ Needed for OIDC login
  contents: read

env:
  BuildConfiguration: Release
  BuildPlatform: "Any CPU"

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup NuGet
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      # 3️⃣ Restore NuGet packages
      - name: Restore NuGet packages
        shell: pwsh
        run: |
          $solution = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Filter *.sln -Recurse | Select-Object -First 1
          if (-not $solution) {
            Write-Error "❌ No solution file found in repository!"
            exit 1
          }
          Write-Host "✅ Found solution: $($solution.FullName)"
          nuget restore $solution.FullName

      # 4️⃣ Build and Publish ASP.NET Framework project
      - name: Build and Publish
        shell: pwsh
        run: |
          $project = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Filter *.csproj -Recurse | Select-Object -First 1
          if (-not $project) {
            Write-Error "❌ No .csproj file found!"
            exit 1
          }

          Write-Host "🔧 Building project: $($project.FullName)"
          $publishDir = Join-Path $env:RUNNER_TEMP "publish_output"

          msbuild $project.FullName `
            /p:Configuration=$env:BuildConfiguration `
            /p:Platform="$env:BuildPlatform" `
            /p:DeployOnBuild=true `
            /p:WebPublishMethod=FileSystem `
            /p:DeleteExistingFiles=true `
            /p:publishUrl="$publishDir"

          Write-Host "✅ Build completed. Published to: $publishDir"
          Get-ChildItem $publishDir

      # 5️⃣ Login to Azure using OIDC
      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 6️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "SFinfotechwebapp01"              # 👈 Replace with your Web App name
          package: ${{ runner.temp }}/publish_output  # 👈 Folder to deploy

      # 7️⃣ (Optional) Upload publish folder as artifact (for debugging)
      - name: Upload publish output (optional)
        uses: actions/upload-artifact@v4
        with:
          name: publish_output
          path: ${{ runner.temp }}/publish_output
