name: Build and Deploy ASP.NET App to Azure Web App (OIDC + Fixed Package)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write      # 👈 Required for OIDC auth
  contents: read

env:
  Solution: '**/*.sln'
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # --------------------------
    # 1️⃣ Checkout source
    # --------------------------
    - name: Checkout Code
      uses: actions/checkout@v4

    # --------------------------
    # 2️⃣ Setup NuGet
    # --------------------------
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    # --------------------------
    # 3️⃣ Restore NuGet Packages
    # --------------------------
    - name: Restore Packages
      run: nuget restore "$env:Solution"
      shell: pwsh

    # --------------------------
    # 4️⃣ Setup MSBuild
    # --------------------------
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # --------------------------
    # 5️⃣ Build and Publish (FileSystem)
    # --------------------------
    - name: Build and Publish Solution
      run: |
        msbuild $env:Solution `
          /p:DeployOnBuild=true `
          /p:WebPublishMethod=FileSystem `
          /p:PublishUrl="${{ github.workspace }}\publish" `
          /p:SkipInvalidConfigurations=true `
          /p:Platform="$env:BuildPlatform" `
          /p:Configuration="$env:BuildConfiguration"
      shell: pwsh

    # --------------------------
    # 6️⃣ Upload Build Artifact (optional)
    # --------------------------
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp-publish
        path: ${{ github.workspace }}/publish

    # --------------------------
    # 7️⃣ Azure Login (OIDC)
    # --------------------------
    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # --------------------------
    # 8️⃣ Deploy to Azure Web App
    # --------------------------
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'SFinfotechwebapp01'
        package: ${{ github.workspace }}/publish
