name: Build ASP.NET Framework App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      BuildPlatform: 'Any CPU'
      BuildConfiguration: 'Release'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: 'latest'

    - name: Restore NuGet packages
      run: |
        $solution = Get-ChildItem -Path . -Recurse -Filter *.sln | Select-Object -First 1
        if (-not $solution) { throw "No .sln file found in repo" }
        Write-Host "Restoring packages for $($solution.FullName)"
        nuget restore "$($solution.FullName)"
      shell: pwsh

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[17.0,)'   # VS 2022 or later

    - name: Build solution
      run: |
        $solution = Get-ChildItem -Path . -Recurse -Filter *.sln | Select-Object -First 1
        if (-not $solution) { throw "No .sln file found in repo" }
        msbuild "$($solution.FullName)" /p:Configuration=$env:BuildConfiguration /p:Platform="$env:BuildPlatform" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(pwd)\drop"
      shell: pwsh

    - name: Copy JSON config files
      run: |
        mkdir -p drop\json
        Get-ChildItem -Path . -Recurse -Include *.json | Copy-Item -Destination drop\json
      shell: pwsh

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: drop
        path: drop
