name: Build and Deploy ASP.NET App to Azure Web App (OIDC + Extract PackageTmp)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write      # 👈 Required for OIDC
  contents: read

env:
  Solution: '**/*.sln'
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # --------------------------
    # 1️⃣ Checkout
    # --------------------------
    - name: Checkout Code
      uses: actions/checkout@v4

    # --------------------------
    # 2️⃣ Setup NuGet
    # --------------------------
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    # --------------------------
    # 3️⃣ Restore Packages
    # --------------------------
    - name: Restore NuGet Packages
      run: nuget restore "$env:Solution"
      shell: pwsh

    # --------------------------
    # 4️⃣ Setup MSBuild
    # --------------------------
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # --------------------------
    # 5️⃣ Build & Package (WebDeploy)
    # --------------------------
    - name: Build Solution (MSDeploy Package)
      run: |
        msbuild $env:Solution `
          /p:DeployOnBuild=true `
          /p:WebPublishMethod=Package `
          /p:PackageAsSingleFile=true `
          /p:SkipInvalidConfigurations=true `
          /p:PackageLocation="${{ github.workspace }}\package" `
          /p:Platform="$env:BuildPlatform" `
          /p:Configuration="$env:BuildConfiguration"
      shell: pwsh

    # --------------------------
    # 6️⃣ Extract WebDeploy Package
    # --------------------------
    - name: Extract PackageTmp folder
      run: |
        $pkg = Get-ChildItem "${{ github.workspace }}\package" -Filter *.zip | Select-Object -First 1
        if (-not $pkg) { throw "No MSDeploy package found in package folder." }
        Expand-Archive -Path $pkg.FullName -DestinationPath "${{ github.workspace }}\extracted"
      shell: pwsh

    # --------------------------
    # 7️⃣ Upload Artifact (optional)
    # --------------------------
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp-package
        path: ${{ github.workspace }}/extracted/PackageTmp

    # --------------------------
    # 8️⃣ Azure Login (OIDC)
    # --------------------------
    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # --------------------------
    # 9️⃣ Deploy to Azure Web App
    # --------------------------
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'SFinfotechwebapp01'
        package: ${{ github.workspace }}/extracted/PackageTmp
