name: Build and Deploy ASP.NET Framework App to Azure WebApp (OIDC)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write        # ✅ Required for OIDC login
  contents: read

env:
  BuildConfiguration: Release
  BuildPlatform: "Any CPU"

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup NuGet
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      # 3️⃣ Restore NuGet packages (auto-detect .sln)
      - name: Restore NuGet packages
        shell: pwsh
        run: |
          $solution = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Filter *.sln -Recurse | Select-Object -First 1
          if (-not $solution) {
            Write-Error "❌ No solution file found in repository!"
            exit 1
          }
          Write-Host "✅ Found solution: $($solution.FullName)"
          nuget restore $solution.FullName

      # 4️⃣ Build and publish using full MSBuild path
      - name: Build and Publish
        shell: pwsh
        run: |
          $project = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Filter *.csproj -Recurse | Where-Object { $_.FullName -match 'Website|WebApplication' } | Select-Object -First 1
          if (-not $project) {
            Write-Error "❌ No .csproj file found for web app!"
            exit 1
          }

          Write-Host "🔧 Building project: $($project.FullName)"
          $publishDir = Join-Path $env:RUNNER_TEMP "publish_output"

          # Ensure directory exists
          if (-not (Test-Path $publishDir)) {
            New-Item -ItemType Directory -Path $publishDir | Out-Null
            Write-Host "📁 Created directory: $publishDir"
          }

          # Find MSBuild.exe
          $msbuildPaths = @(
            "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe",
            "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe"
          )
          $msbuild = $msbuildPaths | Where-Object { Test-Path $_ } | Select-Object -First 1
          if (-not $msbuild) {
            Write-Error "❌ MSBuild.exe not found on this agent!"
            exit 1
          }

          Write-Host "🛠 Using MSBuild: $msbuild"
          & $msbuild $project.FullName `
            /p:Configuration=$env:BuildConfiguration `
            /p:Platform="$env:BuildPlatform" `
            /p:DeployOnBuild=true `
            /p:WebPublishMethod=FileSystem `
            /p:DeleteExistingFiles=true `
            /p:publishUrl="$publishDir" `
            /p:AutoParameterizationWebConfigConnectionStrings=false

          if (Test-Path $publishDir) {
            Write-Host "✅ Build completed. Published to: $publishDir"
            Get-ChildItem -Recurse $publishDir
          } else {
            Write-Error "❌ Publish folder not found! Check MSBuild output above for any errors."
            exit 1
          }


      # 5️⃣ Login to Azure using OIDC (no secrets required)
      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 6️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "SFinfotechwebapp01"              # 👈 Your Web App name
          package: ${{ runner.temp }}/publish_output  # 👈 Folder to deploy

      # 7️⃣ (Optional) Upload publish folder for debugging
      - name: Upload publish output (optional)
        uses: actions/upload-artifact@v4
        with:
          name: publish_output
          path: ${{ runner.temp }}/publish_output
